/**
 * Central icon registry for the Octavia design system.
 *
 * Every UI icon in the site comes from Heroicons (24px outline) and is
 * re-exported here under a stable, semantic name so components never import
 * an icon library directly. Brand marks (social networks) are inline SVGs
 * because Heroicons intentionally ships no brand logos.
 *
 * Usage: import { ArrowRight } from "@/site/icons";
 */
import type { SVGProps } from "react";
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  ArrowDownRightIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  ArrowsPointingOutIcon,
  BoltIcon,
  BookOpenIcon,
  BookmarkIcon,
  BriefcaseIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  CakeIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRightIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClockIcon,
  CloudIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CpuChipIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyDollarIcon,
  DevicePhoneMobileIcon,
  DocumentDuplicateIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  FilmIcon,
  FireIcon,
  FunnelIcon,
  GlobeAltIcon,
  GlobeAmericasIcon,
  HandThumbUpIcon,
  HeartIcon,
  HomeIcon,
  KeyIcon,
  LightBulbIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MapPinIcon,
  PaperAirplaneIcon,
  PhoneArrowUpRightIcon,
  PhoneIcon,
  QuestionMarkCircleIcon,
  RectangleGroupIcon,
  RocketLaunchIcon,
  ScaleIcon,
  ServerStackIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  Square3Stack3DIcon,
  Squares2X2Icon,
  StarIcon,
  SunIcon,
  TableCellsIcon,
  TrophyIcon,
  TruckIcon,
  UserIcon,
  UsersIcon,
  VideoCameraIcon,
  ViewfinderCircleIcon,
  WifiIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

export type IconProps = SVGProps<SVGSVGElement> & { title?: string; titleId?: string };

export {
  AcademicCapIcon as GraduationCap,
  AdjustmentsHorizontalIcon as Sliders,
  ArchiveBoxIcon as Container,
  ArrowDownRightIcon as ArrowDownRight,
  ArrowDownTrayIcon as Download,
  ArrowLeftIcon as ArrowLeft,
  ArrowPathRoundedSquareIcon as Workflow,
  ArrowRightIcon as ArrowRight,
  ArrowTopRightOnSquareIcon as ExternalLink,
  ArrowTrendingDownIcon as TrendingDown,
  ArrowTrendingUpIcon as Activity,
  ArrowTrendingUpIcon as TrendingUp,
  ArrowUpIcon as ArrowUp,
  ArrowUpRightIcon as ArrowUpRight,
  ArrowsPointingOutIcon as Maximize2,
  BoltIcon as Dumbbell,
  BoltIcon as Zap,
  BookOpenIcon as BookOpen,
  BookmarkIcon as Bookmark,
  BriefcaseIcon as Briefcase,
  BuildingLibraryIcon as Landmark,
  BuildingOffice2Icon as Building,
  BuildingOffice2Icon as Factory,
  BuildingOfficeIcon as Building2,
  CakeIcon as Utensils,
  CalendarDaysIcon as Calendar,
  ChartBarIcon as BarChart3,
  ChartPieIcon as Gauge,
  ChatBubbleBottomCenterTextIcon as Quote,
  ChatBubbleLeftRightIcon as MessageSquare,
  CheckBadgeIcon as UserCheck,
  CheckCircleIcon as CheckCircle,
  CheckCircleIcon as CheckCircle2,
  CheckIcon as Check,
  ChevronDownIcon as ChevronDown,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  ChevronUpIcon as ChevronUp,
  CircleStackIcon as Database,
  ClockIcon as Clock,
  CloudIcon as Cloud,
  CodeBracketIcon as Braces,
  CodeBracketIcon as Code,
  CodeBracketIcon as Code2,
  CodeBracketSquareIcon as ApiIcon,
  CodeBracketSquareIcon as FileCode,
  Cog6ToothIcon as Settings,
  CommandLineIcon as Binary,
  CommandLineIcon as Terminal,
  CpuChipIcon as Bot,
  CpuChipIcon as Cpu,
  CubeIcon as Box,
  CubeTransparentIcon as Boxes,
  CurrencyDollarIcon as DollarSign,
  DevicePhoneMobileIcon as Smartphone,
  DocumentDuplicateIcon as Copy,
  DocumentTextIcon as FileJson,
  DocumentTextIcon as FileText,
  EnvelopeIcon as Mail,
  ExclamationTriangleIcon as AlertTriangle,
  EyeIcon as Eye,
  FilmIcon as Film,
  FireIcon as Flame,
  FunnelIcon as Filter,
  GlobeAltIcon as Globe,
  GlobeAmericasIcon as Globe2,
  HandThumbUpIcon as ThumbsUp,
  HeartIcon as HeartHandshake,
  HeartIcon as HeartPulse,
  HeartIcon as Stethoscope,
  HomeIcon as Home,
  KeyIcon as Key,
  LightBulbIcon as Brain,
  LightBulbIcon as Lightbulb,
  ListBulletIcon as List,
  LockClosedIcon as Lock,
  MagnifyingGlassIcon as Search,
  MapIcon as Compass,
  MapPinIcon as MapPin,
  PaperAirplaneIcon as Plane,
  PaperAirplaneIcon as Send,
  PhoneArrowUpRightIcon as PhoneCall,
  PhoneIcon as Phone,
  QuestionMarkCircleIcon as HelpCircle,
  RectangleGroupIcon as Layout,
  RocketLaunchIcon as Rocket,
  ScaleIcon as Scale,
  ServerStackIcon as Server,
  ShareIcon as GitBranch,
  ShareIcon as Network,
  ShareIcon as Share2,
  ShieldCheckIcon as Shield,
  ShieldCheckIcon as ShieldCheck,
  ShieldExclamationIcon as ShieldAlert,
  ShoppingBagIcon as ShoppingBag,
  ShoppingCartIcon as ShoppingCart,
  SignalIcon as Radio,
  SparklesIcon as Sparkles,
  SpeakerWaveIcon as Headphones,
  Square3Stack3DIcon as Layers,
  Squares2X2Icon as Component,
  Squares2X2Icon as Grid,
  Squares2X2Icon as LayoutDashboard,
  StarIcon as Star,
  SunIcon as Sprout,
  TableCellsIcon as FileSpreadsheet,
  TrophyIcon as Award,
  TruckIcon as Car,
  TruckIcon as Truck,
  UserIcon as User,
  UsersIcon as Users,
  VideoCameraIcon as Video,
  ViewfinderCircleIcon as Target,
  WifiIcon as Wifi,
  XMarkIcon as X,
};

/** Brand marks — not available in Heroicons, kept as minimal inline SVGs. */
export const Linkedin = (props: IconProps) => (
  <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}>
    <path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.35V9h3.41v1.56h.05a3.74 3.74 0 0 1 3.37-1.85c3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.07 2.07 0 1 1 0-4.13 2.07 2.07 0 0 1 0 4.13zM7.12 20.45H3.55V9h3.57v11.45zM22.22 0H1.77C.79 0 0 .77 0 1.72v20.55C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.73V1.72C24 .77 23.2 0 22.22 0z" />
  </svg>
);

export const Twitter = (props: IconProps) => (
  <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}>
    <path d="M18.9 2H22l-6.77 7.73L23.2 22h-6.24l-4.88-6.38L6.5 22H3.4l7.24-8.27L2.8 2h6.4l4.41 5.83L18.9 2zm-1.1 18.1h1.73L7.3 3.8H5.45L17.8 20.1z" />
  </svg>
);

export const Facebook = (props: IconProps) => (
  <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}>
    <path d="M24 12.07C24 5.4 18.63 0 12 0S0 5.4 0 12.07C0 18.1 4.39 23.1 10.13 24v-8.44H7.08v-3.49h3.05V9.41c0-3.02 1.79-4.7 4.53-4.7 1.31 0 2.68.24 2.68.24v2.96h-1.51c-1.49 0-1.96.93-1.96 1.89v2.27h3.33l-.53 3.49h-2.8V24C19.61 23.1 24 18.1 24 12.07z" />
  </svg>
);
